travis:
  secure:
    BINSTAR_TOKEN: BPL5gIj5jfb4g01o5nq8vcJUKlcLbkgmbSaj/o3dgFs1UZ0R6XXAcxxW0vCP+z1KtG0bQvRFtO2DKgxbA71I54w8Ha+BreE+umBmuzz8j+2Es2Rg1e8PcqndkWEMpDSKJN4VLWAFOMmnUbS8IqZgtbOPOHcUNas2S9hd1AmiK5MpVA18veWm0aLrS+fCJlzosnqqgnvb9QlV49AK/rx+65dfTuFnfFMUZYivX/S7u3Po/rgtg4UrL8ZWacz4SP8bcMjRW4VD6HSZP1IdLx6HrgR3qooilxaEkLCz2PHxz89Oad8pEZC6CtNxqTyquILovgi3nVAS86omf6fq67nkKHkoUHHdCx6fFoifDV3QwbkrYCGW15+IXdPafAiKzZe6Q+MNluCE6MoyQxPpukdwOKWDN6bfm6RUcGBlZwaYO2tXw7U2EQhf/223H4Aac4OWeT7TzDY//8hmPM1ldOnPa41V8xHzu+jEShp5E5PnLlXfAfBOMUsTy+tNiHxeEAuqeddavhs3cRKQ7zB3E+W3hEKNwvAer0B+64I9dEU1ixH6YcXVMuQDJwE7ft9P6gxmUiEra3Z17AVNnwRRl9bNAvk/EXWLaxWjikFJYt/9/X1fz0nWRZm0gVlBMByvopv+Ktk1Mv/u9ZUXkq6EIPmwzpE5G1Dq/IW1XkOZ/4KlAO4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
